### ISSUE TITLE
App increse size on disk

### ISSUE THREAD

**Issue by RoberV** [smartlook/smartlook-android-sdk#45]
Hi,
I'm using the library, and in my app installation I have seen that app has a 6GB size on phone memory.
I create a backup of the app installation. And I jhave seen that there are a lot of sessions folder, with a folder named video_images with images and videos, it increase the use of memory to 6GB.
What is the problem?
I'm only calling:
Smartlook.setupAndStartRecording("Mykey") 
Smartlook.setUserIdentifier(email)
In the first activity onCreate

**Comment by SenNeonoveNoci** [comment]
Hi @RoberV,

when the device is not on WIFI we are storing video recordings offline and will upload them as soon as the application starts with wifi connection. 

The number of 6GB sounds pretty large because we are checking for free memory left and will not write above some limit. But when you have really lot of free space even this value can be correct. We gonna introduce some hard limit so this doesn't happen.

**Comment by adamblack** [comment]
Hi @RoberV ,

it is fixed in new version 1.4.2
