### ISSUE TITLE
New to 

### ISSUE THREAD

**Issue by jsun-dd** [smartlook/smartlook-android-sdk#52]
Hi there I'm on an Android native app new to Smartlook. After [installing the sdk](https://smartlook.github.io/docs/sdk/android/) in build.gradle I'm not able to get my IDE to auto-suggest an import for `Smartlook.setupAndStartRecording` as described in the [setup doc](https://smartlook.github.io/docs/sdk/android/).

Looking at the API docs and sources, I don't see any way to find out the package name either.
Can you let me know what the expected import package is for the `Smartlook` class?

**Comment by SenNeonoveNoci** [comment]
Hi @jsun-dd,

so you have added our maven repository to your apps `build.gradle`, added SDK implementation into your project `build.gradle` and synced the Gradle files with the project and still cannot see `Smartlook.setupAndStartRecording`, am I right?

What happens when you place:
```
Smartlook.setupAndStart(YOUR_API_KEY);
```
into your projects `Application` class. Does your project build? If it doesn't what is the error message?

**Comment by jsun-dd** [comment]
Hi there,

Yes that is exactly right.
It says "Unresolved reference: Smartlook". Which isn't surprising since I
haven't added the import for it.

What is the package name for Smartlook so I can add the import?

Janet

**Comment by adamblack** [comment]
Hi @jsun-dd ,

to answer your question: `import com.smartlook.sdk.smartlook.Smartlook`

However it seems weird that IDE is not able to resolve that automatically. Let us know if that helped. Otherwise I would say it might be some gradle sync issue.

**Comment by jsun-dd** [comment]
Hi Adam,
That fixed it.

It was just an IDE issue. Thank you!

Janet

**Comment by adamblack** [comment]
Glad it helped. :] - Fell free to open new issue in case of any problems.
